### ISSUE TITLE
Hydration error on Nextra V3

### ISSUE THREAD

**Issue by whitedark9** [shuding/nextra-docs-template#86]
### How the error occurs

I switch to light theme. Then, reload the localhost. And hydration error occurs.<br>
The error does not occur on reloading with dark theme and system theme.

#### Browser
Microsoft Edge

#### Dependence
```json  
    "next": "^14.2.3",
    "nextra": "^3.2.4",
    "nextra-theme-docs": "^3.2.4",
    "react": "^18.3.1",
    "react-dom": "^18.3.1"
```

#### Error code

```
react-dom.development.js:20782  Uncaught Error: There was an error while hydrating this Suspense boundary. Switched to client rendering.
    at updateDehydratedSuspenseComponent (react-dom.development.js:20782:1)
    at updateSuspenseComponent (react-dom.development.js:20401:1)
    at beginWork (react-dom.development.js:21663:1)
    at beginWork$1 (react-dom.development.js:27465:1)
    at performUnitOfWork (react-dom.development.js:26596:1)
    at workLoopConcurrent (react-dom.development.js:26582:1)
    at renderRootConcurrent (react-dom.development.js:26544:1)
    at performConcurrentWorkOnRoot (react-dom.development.js:25777:1)
    at workLoop (scheduler.development.js:266:1)
    at flushWork (scheduler.development.js:239:1)
    at MessagePort.performWorkUntilDeadline (scheduler.development.js:533:1)
```

**Comment by whitedark9** [comment]
The error is gone now. I don't know how.
